// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RegistroDePonto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612195728_Atualizado banco")]
    partial class Atualizadobanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Funcionario", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Matricula"));

                    b.Property<TimeSpan>("EntradaManha")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("EntradaTarde")
                        .HasColumnType("time(6)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("SaidaManha")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("SaidaTarde")
                        .HasColumnType("time(6)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Matricula");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("RegistroPonto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("HoraBatida")
                        .HasColumnType("time(6)");

                    b.Property<int>("MatriculaFuncionario")
                        .HasColumnType("int");

                    b.Property<string>("TipoBatida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaFuncionario");

                    b.ToTable("RegistrosPonto");
                });

            modelBuilder.Entity("RegistroPonto", b =>
                {
                    b.HasOne("Funcionario", "Funcionario")
                        .WithMany("RegistrosPonto")
                        .HasForeignKey("MatriculaFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Funcionario", b =>
                {
                    b.Navigation("RegistrosPonto");
                });
#pragma warning restore 612, 618
        }
    }
}
